### ISSUE TITLE
Unable to build a valid .wbn file using the `webbundle` crate

### ISSUE THREAD

**Issue by antonispoulakis** [google/webbundle#6]
I am trying to build a `.wbn` using the webbundle crate but cannot make it load on Chrome.

-----

I have tried using the `exchanges_from_dir` function with the same files as in `tests/builder` [here](https://github.com/google/webbundle/tree/main/webbundle/tests/builder). This creates the .wbn file and I am able to use `dump-bundle` from the cli to view the contents, but once I try to load the file into Chrome I get 
```
"Failed to read metadata of Web Bundle file: Invalid bundle length."
``` 
in the console.

My code for this case is:

```rust
let bundle = Bundle::builder()
  .version(Version::VersionB2)
  .exchanges_from_dir("./test")
  .await?
  .build?;

let write = std::io::BufWriter::new(std::fs::File::create("./local.wbn")?);
data.write_to(write)?;
```

Using the cli tool, this still doesn't seem to work, but probably I am missing something:
```bash
gen-bundle -dir ./test -o local.wbn
```
I get the following error in Chrome when loading the .wbn:
```
Failed to read metadata of Web Bundle file: Index section: exchange URL "./" is not valid. (Relative URLs are not allowed in this context.)
```

-----

I have also tried using a URL with exchanges to build the `https://google.com` page (just passing this as the primaryURL and an exchange). In this case, the `dump-bundle` cli command throws:
```
"bundle.index: failed to decode index section map header: cbor: Expected type 160, got type 96"
```

and the same error in the chrome console as above. In this case, I am doing a fetch on the `https://google.com` URL and setting the response in the exchange.

When using the cli tool, this works fine:
```bash
# google_urls.txt only contains https://google.com
gen-bundle  -URLList google_urls.txt -primaryURL https://google.com -o google.wbn
```

-----

Would it be possible to provide working examples for both using a local path and a remote URL?

**Comment by hayatoito** [comment]
Thanks for filing an issue. Ack.
Let me take a look closely this week and try to provide working examples.
(Or fix a bug and release a new version).

**Comment by hayatoito** [comment]
I guess you are trying "Navigate-to-Bundle" feature (e.g. Drag and drop a created wbn to a browser's window), which is explained in https://web.dev/web-bundles/.

This feature, "Navigate-to-Bundle", requires an *absolute URL* for each resource in Web Bundle.

Unfortunately, it seems I dropped "absolute URL" support from `webbundle::Builder::exchange_from_dir()` in version 0.32 or later. Now that only supports a "relative URL".

- https://docs.rs/webbundle/0.3.2/webbundle/struct.Builder.html
  - exchanges_from_dir() can take only `dir`.
- https://docs.rs/webbundle/0.2.0/webbundle/index.html
  - exchanges_from_dir() can take `base_url` + `dir`.

That's a reason Chrome complains because "Navigate-to-Support" requires an absolute URL. 

As a workaround, to create a web bundle where each resource has an absolute URL:

- webbundle crate: Use [webbundle::Builder::exchange()](https://docs.rs/webbundle/0.3.2/webbundle/struct.Builder.html#method.exchange)
  This is a most flexible, low-level API. You can pass any string as URL.

- CLI: Since you already use `gen-bundle` tools (Written in Go), I think you can pass a base-URL option, as follows:

  `gen-bundle -dir static -baseURL https://example.com/ -o foo.wbn -primaryURL https://example.com/`
   (https://github.com/WICG/webpackage/blob/main/go/bundle/README.md)

**Comment by antonispoulakis** [comment]
Hi @hayatoito, thanks for your reply. I'm only really interested in creating the `.wbn` file from the `webbundle` crate using the remove urls and the `exchange()`

I have tried using `exchange()`, but I still get the error I describe above in the second section. 

Here's the snippet I'm using:

```rust
  let primary_url = "https://www.google.com/".parse::<Uri>().unwrap();
  let ex_req = Request::from("https://www.google.com/".to_string());
  let ex_res = reqwest::get("https://www.google.com/").await?.bytes().await?.to_vec();

  let write = BufWriter::new(File::create("./google.wbn")?);

  Bundle::builder()
  .version(Version::VersionB2)
  .primary_url(primary_url)
  .exchange((ex_req, ex_res, ContentType::html()).into())
  .build()?
  .write_to(write)?;
```

Maybe I'm passing something wrong to the `exchange` function?

**Comment by hayatoito** [comment]
Thanks for trying it. My expectation is "That should work". But I'm afraid something is wrong.

Let me add some examples to webbundle/webbundle/examples directory and confirm the created bundle is surely loaded in Chrome. That's my TODO. Noted!

**Comment by hayatoito** [comment]
Quick update: I've confirmed that webbundle crate produces a *broken* bundle if it contains primary URL. I'm afraid this bug has been there since we supported b2, where primary URL became optional.

Let me fix that.

**Comment by hayatoito** [comment]
Fixed the issue: https://github.com/google/webbundle/commit/631f6a804a157019d0d842b791d511bec14a34f4

webbundle v0.5.0 shouldn't have an issue, I think.

I've confirmed that a bundle generated by https://github.com/google/webbundle/blob/main/webbundle/examples/create-webbundle.rs is successully loaded in Chrome (by drag & drop).

I appreciate if you can confirm it. Thanks!

**Comment by antonispoulakis** [comment]
Sorry for the late reply; the newest version works, thanks!

**Comment by hayatoito** [comment]
Thanks!
